[programs.localnet]
likes = "Av2WRMKbkw1ircKXbxh9djiBUhJzasHEhXXHkcz3xVUw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://lingering-lingering-mountain.solana-devnet.quiknode.pro/fbbd36836095686bd9f580212e675aaab88204c9/"
wallet = "/Users/nathanshirley/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"